name: Android Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore/your_signing_keystore.jks'
            encodedString: ${{ secrets.KEYSTORE }}
      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
            java-version: 11
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run Tests
        run: ./gradlew test
      - name: build prod
        run: ./gradlew build
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
            SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}