name: Android Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11

      - name: Enable Gradle
        run: chmod +x gradlew

      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble
